# Generated by Django 4.1.8 on 2023-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
