# Generated by Django 4.1.8 on 2023-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_basket_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
