# Generated by Django 4.1.8 on 2023-05-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_basket_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='broadcast_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
